name: Build and Deploy to Pages
on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: codeberg-tiny
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  pip install --upgrade pip
                  pip install mkdocs-material

            - name: Build documentation
              run: mkdocs build

            - name: Deploy to Codeberg Pages
              run: |
                  # Configure git
                  git config --global user.name "Codeberg Pages"
                  git config --global user.email "noreply@codeberg.org"

                  # Create/checkout pages branch
                  git checkout --orphan pages

                  # Remove all files except site/
                  find . -maxdepth 1 -not -name 'site' -not -name '.git' -not -name '.' -exec rm -rf {} +

                  # Move site contents to root
                  mv site/* .
                  rmdir site

                  # Add and commit
                  git add .
                  git commit -m "Deploy documentation"

                  # Push to pages branch
                  git push -f origin pages
